library(seqinr)
library(tidyverse)
library(ggplot2)
library(readxl)
library(ggrepel)
library(ggsci)
theme_publication<-theme_classic()+
  theme(text = element_text(size=10, family = "Arial"),
        panel.background = element_rect(colour="black", linewidth=0.5),
        legend.position = "bottom",
        strip.background = element_blank())

outdir<-"data/execute_MLDE_benchmark/2nd_round_MLDE_input_Fitness_files/"
### SpCas9 ###
Fit_norm<-read_csv("data/MLDE_train_test_datasets/SpCas9_fitness_norm.csv")
Fit_norm<- Fit_norm %>% gather(sg, Fitness_n, 2:3)
## input data in Supplementary table S1
Fit<-read_csv("data/execute_MLDE_benchmark/SpCas9_Fitness.csv")
Fit<-left_join(Fit, Fit_norm)
test_sample<-read_csv("data/MLDE_train_test_datasets/SpCas9_test_sample.data")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SpCas9_Sg5_CLADEarDCA_Fitness_georgiev_p2/20230617-164342/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="Sg5") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="Sg5") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SpCas9_Sg5_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SpCas9_Sg5_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-125451/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="Sg5") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="Sg5") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SpCas9_Sg5_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SpCas9_Sg8_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-125551/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="Sg8") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="Sg8") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SpCas9_Sg8_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SpCas9_Sg5_CLADEEVmutation_Fitness_georgiev_p2/20230617-164441/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="Sg5") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="Sg5") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SpCas9_Sg5_EVmutation_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SpCas9_Sg8_CLADEarDCA_Fitness_georgiev_p2/20230617-165016/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="Sg8") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="Sg8") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SpCas9_Sg8_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SpCas9_Sg8_CLADEEVmutation_Fitness_georgiev_p2/20230617-165118/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="Sg8") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="Sg8") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SpCas9_Sg8_EVmutation_CLADETOP.csv"))

### SaCas9_1296 
Fit_norm<-read_csv("data/MLDE_train_test_datasets/SaCas9_887888887985986988989991_Fitness_norm.csv")
Fit_norm<- Fit_norm %>% gather(sg, Fitness_n, 2:4)
Fit<-read_csv("data/execute_MLDE_benchmark/Sa1296_Fitness.csv")
Fit<-left_join(Fit, Fit_norm)
test_sample<-read_csv("data/MLDE_train_test_datasets/SaCas9_887888889985986988989991_fixed_test_set.txt")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_ACAAGT_CLADEEarDCA_Fitness_georgiev_p2/20230617-172752/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="ACAAGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="ACAAGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_ACAAGT_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas91296_ACAAGT_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-130040/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="ACAAGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="ACAAGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_ACAAGT_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_ACAAGT_CLADEEVmutation_Fitness_georgiev_p2/20230617-172901/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="ACAAGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="ACAAGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_ACAAGT_EVmutation_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_GGTGGT_CLADEEarDCA_Fitness_georgiev_p2/20230617-173424/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="GGTGGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="GGTGGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_GGTGGT_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas91296_GGTGGT_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-130132/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="GGTGGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="GGTGGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_GGTGGT_EVarDCA_CLADE2TOP.csv"))


t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_GGTGGT_CLADEEVmutation_Fitness_georgiev_p2/20230617-173526/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="GGTGGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="GGTGGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_GGTGGT_EVmutation_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_TGGAGT_CLADEarDCA_Fitness_georgiev_p2/20230617-174101/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="TGGAGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="TGGAGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_TGGAGT_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas91296_TGGAGT_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-130228/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="TGGAGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="TGGAGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_TGGAGT_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_TGGAGT_CLADEEVmutation_Fitness_georgiev_p2/20230617-174205/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="TGGAGT") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="TGGAGT") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas91296_TGGAGT_EVmutation_CLADETOP.csv"))

### Sa8000 ###
Fit_norm<-read_csv("data/MLDE_train_test_datasets/SaCas9_8888889909_Fitness_norm.csv")
Fit_norm<- Fit_norm %>% gather(sg, Fitness_n, 2:5)
Fit<-read_csv("data/execute_MLDE_benchmark/Sa8000_Fitness.csv")
Fit<-left_join(Fit, Fit_norm)
test_sample<-read_csv("data/MLDE_train_test_datasets/Sa8000_test_sample2.data")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_DTp56libD18_CLADEEarDCA_Fitness_georgiev_p2/20230617-170549/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="DTp56libD18") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="DTp56libD18") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas98000_DTp56libD18_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas98000_DTp56libD18_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-125745/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="DTp56libD18") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="DTp56libD18") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas98000_DTp56libD18_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_DTp56libD18_CLADEEVmutation_Fitness_georgiev_p2/20230617-170647/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="DTp56libD18") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="DTp56libD18") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas98000_DTp56libD18_EVmutation_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_DTp58libD21_CLADEarDCA_Fitness_georgiev_p2/20230617-172027/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="DTp58libD21") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="DTp58libD21") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas98000_DTp58libD21_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas9_DTp58libD21_CLADEarDCA_Fitness_georgiev_p2/20230617-172027/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="DTp58libD21") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="DTp58libD21") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas98000_DTp58libD21_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/SaCas98000_DTp58libD21_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-125937/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit%>% filter(sg=="DTp58libD21") %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(sg=="DTp58libD21") %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "SaCas98000_DTp58libD21_EVarDCA_CLADE2TOP.csv"))


### PhoQ ###
Fit<-read_csv("data/MLDE_train_test_datasets/PhoQ_zeroshot.csv")
Fit<-Fit[, 2:8]
colnames(Fit)[1]<-"AACombo"
test_sample<-read_csv("data/MLDE_train_test_datasets/PhoQ_test_sample.data")
colnames(test_sample)<-c("AACombo", "Fitness", "Fitness_n")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/PhoQ_CLADEEarDCA_Fitness_georgiev_p2/20230617-161739/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "PhoQ_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/PhoQ_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-125204/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "PhoQ_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/PhoQ_CLADEEVmutation_Fitness_georgiev_p2/20230617-161850/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "PhoQ_EVmutation_CLADETOP.csv"))

### GFP ###
Fit<-read_csv("data/MLDE_train_test_datasets/GFP_zeroshot.csv")
Fit<-Fit[, 2:8]
colnames(Fit)[1]<-"AACombo"
test_sample<-read_csv("data/MLDE_train_test_datasetsGFP_test_sample.data")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/GFP_CLADEEarDCA_Fitness_georgiev_p2/20230617-151420/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "GFP_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/GFP_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-124549/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "GFP_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/GFP_CLADEEVmutation_Fitness_georgiev_p2/20230617-151649/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "GFP_EVmutation_CLADETOP.csv"))

### PABP ###
Fit<-read_csv("data/MLDE_train_test_datasets/PABP_zeroshot.csv")
Fit<-Fit[, 2:8]
colnames(Fit)[1]<-"AACombo"
test_sample<-read_csv("data/MLDE_train_test_datasets/PABP_test_sample.data")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/PABP_CLADEEarDCA_Fitness_georgiev_p2/20230617-153630/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "PABP_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/PABP_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-124800/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "PABP_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/PABP_CLADEEVmutation_Fitness_georgiev_p2/20230617-153916/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "PABP_EVmutation_CLADETOP.csv"))

### UBE ###
Fit<-read_csv("data/MLDE_train_test_datasets/UBE_zeroshot.csv")
Fit<-Fit[, 2:8]
colnames(Fit)[1]<-"AACombo"
test_sample<-read_csv("data/MLDE_train_test_datasets/UBE_test_sample.data")

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/UBE_CLADEEarDCA_Fitness_georgiev_p2/20230617-155928/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "UBE_arDCA_CLADETOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/UBE_CLADE2EV+arDCA_Fitness_georgiev_p2/20230627-125010/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "UBE_EVarDCA_CLADE2TOP.csv"))

t<-read_csv("data/execute_MLDE_benchmark/execute_1st_round_MLDE_benchmark/UBE_CLADEEVmutation_Fitness_georgiev_p2/20230617-160200/PredictedFitness.csv")
training_variants<- t %>% filter(`InTrainingData?`=="YES") %>% select(AACombo) %>% unlist()
t<-t %>% filter(`InTrainingData?`=="NO") %>% filter(!AACombo %in% test_sample)
t<-left_join(t, Fit %>% select(AACombo, cluster_id, Fitness_n))
t<-t %>% filter(!is.na(Fitness_n)) %>% mutate(rank_p=rank(-PredictedFitness, ties.method = "min"))
nxt_v<-t %>% filter(rank_p<=12) %>% select(AACombo) %>% unlist()
o<- Fit %>% filter(AACombo %in% c(training_variants, nxt_v)) %>% select(AACombo, Fitness_n)
colnames(o)<-c("AACombo", "Fitness")
write_csv(o, paste0(outdir, "UBE_EVmutation_CLADETOP.csv"))
